version: "3.9"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome_grid
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
